Altera envio de pacotes para envio por segundo plano e faz melhorias gerais
scieloorg/spf pull request #38
Opened 2021-12-09 23:59 UTC by rafaelpezzuto

#### O que esse PR faz?
Cria uma task celery para gerenciar o envio de pacotes, assim, ao clicar em enviar, o usuário é redirecionado para uma tela de Eventos em que pode acompanhar o estado do envio (ou fazer outras atividades na aplicação).

Também foi adicionada uma série de melhorias que visam a registrar, com maior precisão, os eventos ocorridos. Erros na tela de busca e na tela de envio passaram a ser registrados.

#### Onde a revisão poderia começar?
Por commits.

#### Como este poderia ser testado manualmente?
1. Instancie a aplicação seguindo o README.md
2. Faça buscas
3. Vá a tela de eventos e observe os registros adicionados
4. Faça envio de pacotes
5. Observe o redirecionamento automático para tela de Eventos
6. Observe na primeira linha o evento de envio de pacote com o Status "Initiated"
7. Após alguns segundos, esse status deverá estar "Completed" (é possível ver isso usando F5, porém, numa próxima alteração, esse elemento será atualizado sozinho, isto é, sem necessidade de F5)

#### Algum cenário de contexto que queira dar?
Esse PR segue o branch `add-migration`, o qual, espera-se, seja incorporado em breve.

### Screenshots
Tela de eventos com o status "Initiated" para um pacote enviado
![image](https://user-images.githubusercontent.com/2096125/145494303-909d08e1-d1e8-4d08-a8f1-42903cafb38e.png)

Tela de eventos com o status "Completed" para um pacote enviado
![image](https://user-images.githubusercontent.com/2096125/145494340-5547f1e2-a76b-4e96-ad79-5058c6a4cb48.png)

Tela de eventos com detalhes dos erros ocorridos
![image](https://user-images.githubusercontent.com/2096125/145494254-dc187bf1-0781-4a6e-ade9-6ad4ffbf636a.png)

#### Quais são tickets relevantes?
#14 

### Referências
N/A

2021-12-10 19:37 UTC, gitnnolabs commented
Validando.....

2021-12-13 11:25 UTC, gitnnolabs commented
@scieloorg/scielo-ps-developers 

Seguindo o **README.md** é esperado que tenhamos uma instância de **postgres**. Sugiro que tenhamos uma docker-compose-dev.yml que contém os containeres necessários para roda a aplicação em ambiente de dev. 

Veja nesse ponto é pre-requisito um postgres local com o seguinte nome ** scl_postgres_1**: 

![Captura de Tela 2021-12-13 às 08 11 05](https://user-images.githubusercontent.com/86991526/145802500-1f40363f-be62-40b9-9d4b-daf5ef336618.png)

Porém, não houve um passo anterior que indica a criação desse contêiner.

Ou adicionarmos uma instrução para criar o container do postgres: 

```shell
 docker run -d \
    --name scl_postgres_1 \
    -e POSTGRES_PASSWORD=postgres \
    -e PGDATA=/var/lib/postgresql/data/pgdata \
    -v ./.data_dev/postgres:/var/lib/postgresql/data \
    postgres
```

2021-12-13 11:30 UTC, gitnnolabs commented
@scieloorg/scielo-ps-developers 

Nesse ponto: 

![Captura de Tela 2021-12-13 às 08 28 06](https://user-images.githubusercontent.com/86991526/145804527-1501a0fb-ed1f-44ee-800c-22257f04a05b.png)

Em que é indicado para criar um arquivo **.env.dev**, seria mais insteressante e fácil termos um arquivo .env.dev-template para que não seja necessário a criação e somente a definição dos valores.

2021-12-13 11:46 UTC, gitnnolabs commented
Ao tentar utilizar o valor padrão do **timeout** do MINIO levanta essa exceção no DSM: 

![Captura de Tela 2021-12-13 às 08 45 59](https://user-images.githubusercontent.com/86991526/145806679-4b83e330-67ff-4499-b712-907257114709.png)

2021-12-13 11:56 UTC, gitnnolabs commented
Talvez essa variável de ambiente **DATABASE_CONNECT_URL**, possa ter um nome que indique que é uma conexão com o MongoDB do OPAC, sugiro algo como **MONGODB_OPAC_DSN**. 

Na lista de variáveis no **README.md**, achei confuso a descrição, veja: _**OPAC/Kernel** database (MongoDB) string connection_, gera dúvida se é uma conexão com o OPAC ou com o Kernel?

2021-12-13 13:41 UTC, rafaelpezzuto commented
> 

O correto é OPAC (dados das coleções Mongo `article`, `issue`, `journal`, etc). `MONGODB_OPAC_DSN` é uma boa sugestão.

2021-12-13 14:25 UTC, gitnnolabs commented
@rafaelpezzuto 

Sobre essa resposta: https://github.com/scieloorg/spf/pull/38#issuecomment-992484502

Sim sim, mas o ponto que estou colocando ai é que o valor **"1000"** está como string e deve ser um interiro(**1000**), e é por isso que está levantando uma exceção!

2021-12-13 14:28 UTC, rafaelpezzuto commented
> @rafaelpezzuto
> 
> Sobre essa resposta: [#38 (comment)](https://github.com/scieloorg/spf/pull/38#issuecomment-992484502)
> 
> Sim sim, mas o ponto que estou colocando ai é que o valor **"1000"** está como string e deve ser um interiro(**1000**), e é por isso que está levantando uma exceção!

Tranquilo. em settings ou em algum lugar nós fazemos `int(variável_de_ambiente ou valor_padrão)`.

Se a variável de ambiente existir, mas for uma string vazia, ele acusa `invalid literal for int() with base 10: ''`

O seja, ele tentou converter a string vazia '' para inteiro.

2021-12-16 14:59 UTC, gitnnolabs requested changes

2021-12-16 14:59 UTC, gitnnolabs commented on app/core/tasks.py
> +    if pid:
Acredito que esse trecho poderia conter uma função para atualização do estado.

2021-12-16 14:59 UTC, gitnnolabs commented on app/core/tasks.py
> +    fs = FileSystemStorage(location=settings.MEDIA_INGRESS_TEMP)
Nesse trecho vejo que podemos ter uma exceção e deixar esse com responsabilidade menor.

2021-12-16 14:59 UTC, gitnnolabs commented on app/core/tasks.py
>  from celery import shared_task, current_task
@rafaelpezzuto 

Esse comentário não é que precisa ser feito agora, mas penso que em algum momento precisará ser feito. 

O celery no django é uma aplicação por isso é comum encontrarmos um módulo ``celery_app.py`` que de fato inicializar o celery como uma app. E com isso é possível usar o celery de forma mais aderente e com alguns benefícios. 

Isso acaba por import que vc tenha esse decorator **shared_task** e o **current_task**, quando o celery está como uma aplicação no Django ele proporciona decoradores para essa aplicação o que te permite mais configuração, por exemplo: 
```
@celery_app.task(bind=True,  max_retries=3)
```

O parâmetro ```bind``` indica que podemos fazer suo da instância do celery nessa tarefa, ou seja, ```self.qualquer_coisa```,  entre outros parâmetros. Com isso também teremos acesso por exemplo ao self.request, entre outro que permeiam a requisição. 

Foi necessário decorar as tasks como @shared_task para garantir que vc possa utilizar a task independente da instância do celery. 

Após escrever esse trecho reparei que vc contém essa aplicação do celery configurada no módulo: https://github.com/scieloorg/spf/blob/main/app/spf/celery.py

Ou seja, ao invés de importar ```from celery import shared_task, current_task``` deve importar ```from spf.celery import app```

E deve alterar os decoradores para 

```
@app.task(bind=True,  max_retries=3)
```

2021-12-16 15:10 UTC, gitnnolabs commented
Como combinado com a equipe e solicitado, não realizei **code review** da `view.py`

2021-12-17 12:43 UTC, gitnnolabs commented
@rafaelpezzuto 

No passo do README.md conta com a criação do usuário com o comando `createsuperuser`, porém ao rodar as fixtures ele sobrescreve pelo ID. Recomendo adicionar esse comando de criação de usuário em um passo posteriror.

2021-12-17 17:59 UTC, gitnnolabs commented on env-TEMPLATE
> +BASES_PATH=/home/rafaeljpd/Data/scl-isis
Show.

2021-12-17 19:04 UTC, gitnnolabs commented on app/core/tasks.py
> +@app.task(bind=True,  max_retries=3)
Show.

2021-12-17 21:03 UTC, rafaelpezzuto commented
@gitnnolabs Precisa de mais alguma alteração muito importante antes de fazer o merge?

2021-12-17 21:14 UTC, rafaelpezzuto commented on app/core/tasks.py
>  from celery import shared_task, current_task
Agora vi que temos acesso ao self.request. isso é bastante bom. depois vou adequar o código

2021-12-17 21:27 UTC, gitnnolabs commented on app/core/tasks.py
>  from celery import shared_task, current_task
Ok

2021-12-17 21:34 UTC, gitnnolabs approved these changes
Funcionou como esperado!!!

2021-12-17 21:36 UTC, merged